[pyprland]
plugins = [
  "scratchpads",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.notes]
animation = "fromBottom"
command = "kitty --class kitty-todoterm -e nvim ~/Desktop/notes.md"
class = "kitty-todoterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 20

[scratchpads.files]
animation = "fromRight"
command = "kitty --class kitty-files -e /home/timothee/apps/yazi/target/release/yazi"
class = "kitty-files"
size = "50% 80%"
max_size = "1000px 100%"
margin = 20
